name: lanx
description: LanX radar secure chat
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cryptography: ^2.9.0
  cryptography_flutter: ^2.3.4
  image_picker: ^1.2.1
  video_player: ^2.11.1
  path_provider: ^2.1.5
  shared_preferences: ^2.5.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true